export const categories: string[] = [
    "Agriculture",
    "Chemicals",
    "Electronics",
    "Energy",
    "Environmental and waste management",
    "Food and beverage",
    "Healthcare",
    "Medical devices and equipment",
    "Mining and metals",
    "Real estate and construction",
    "Textiles",
];



export const subcategories: { [key: string]: string[] } = {

    "Electronics": [
        "Electronics",
        "Electronics",
        "Electronics",
        "Electronics",
        "Electronics",
        "Electronics",
        "Electronics",
        "Electronics",
        "Electronics",
        "Electronics",

    ],
    "Textiles": [

        "Textiles",
        "Textiles",
        "Textiles",
        "Textiles",
        "Textiles",
        "Textiles",
        "Textiles",
        "Textiles",
        "Textiles",
        "Textiles",
        "Textiles",
        "Textiles",

    ],
    'Environmental and waste management': [
        // Add fields here
        "Environmental and waste",
        "Environmental and waste",
        "Environmental and waste",
        "Environmental and waste",
        "Environmental and waste",
        "Environmental and waste",
        "Environmental and waste",
        "Environmental and waste",
        "Environmental and waste",
        "Environmental and waste",
        "Environmental and waste",
        "Environmental and waste",
    ],
    'Mining and metals': [
        // Add fields here
        "Mining",
        "Mining",
        "Mining",
        "Mining",
        "Mining",
        "Mining",
        "Mining",
        "Mining",
        "Mining",
        "Mining",
        "Mining",
    ],


    'Real estate and construction': [
        // Add fields here
        "Real estate",
        "Real estate",
        "Real estate",
        "Real estate",
        "Real estate",
        "Real estate",
        "Real estate",
        "Real estate",
    ],

    "Chemicals": [
        "Chemical Reagent Development",
        "Dewatering & Drying Technology",
        "Catalysis",
        "Trace Elements",
        "Mathematical Chemistry",
        "Dispersion Chemistry",
        "Surface Science",
        "Materials Science & Engineering", //
        "Nanotechnology & Nanomaterials",
        "Surface Chemistry",
        "Metallurgy",
        "Glass Science",
        "Ceramic Engineering",
        "Corrosion",
        "Structural Chemistry",
        "Microencapsulation",
        "Supramolecular Chemistry",
        "Fiber & Textile Engineering",
        "Carbon Materials",
        "Nanotechnology",
        "Biomaterials", //
        "Collagen",
        "Bioplastics",
        "Powder Metallurgy",
        "Powders & Bulk Materials",
        "Refractory Materials",
        "Composite Materials",
        "Electronic, Optical & Magnetic Materials",
        "Dental Materials",
        "Biocatalysis",
        "Marine Chemistry",
        "Coordination Compounds",
        "Inorganic Chemistry",
        "Natural Product Chemistry",
        "Molecular Engineering",
        "Physical Chemistry",
        "iii) Molecular Modeling",
        "Molecular Docking",
        "Chemoinformatics",
        "Biopolymers",
        "Polymer Chemistry",
        "iv) Analytical Chemistry",
        "Deformulation",
        "Separation & Purification",
        "Crystallography",
        "X-Ray Crystallography",
        "Spectroscopy",
        "Atomic Absorption Spectroscopy",
        "Atomic Emission Spectroscopy",
        "UV Spectroscopy",
        "Fluorescence Spectroscopy",
        "IR Spectroscopy",
        "Raman Spectroscopy",
        "NMR Spectroscopy",
        "Circular Dichroism Spectroscopy",
        "Spectrophotometry",
        "Mass Spectrometry",
        "Molecular Imaging",
        "Liquid Chromatography/HPLC",
        "Thermal Analysis",
        "Microcalorimetry",
        "Gas Chromatography",
        "Particle Size Distribution",

        "OpticalRotation",
        "Stable Isotope Analysis",
        "Particle-Induced X-Ray Emission",
        "Electrochemistry",
        "Agricultural Chemistry",
        "Cosmochemistry",
        "Radiochemistry",
        "Astrochemistry",
        "Petrochemistry",
        "v) Solid State Sciences",
        "Condensed Matter Physics",
        "Solid-State Chemistry",
        "Flow Chemistry",
        "Green Chemistry",
        "Organometallic Chemistry",
        "Photochemistry",
        "Quantum Chemistry",
        "Theoretical Chemistry",
        "vi) Organic Chemistry",
        "Retrosynthesis",
        "Thermochemistry",
        "Computational Chemistry",
        "Mechanochemistry",
        "Sonochemistry",
        "Peptide Synthesis",
        "Physical Organic Chemistry",
        "Adhesion Technology",
        "Applied Chemistry",
    ],

    


    "Agriculture": [
        "Plant Science",
        "Agronomy",
        "Plant Breeding",
        "Horticulture",
        "Entomology",
        "Plant Pathology",
        "Soil Science",
        "Weed Science",
        "Agricultural Engineering and Technology",
        "Precision Agriculture",
        "Irrigation and Drainage Engineering",
        "Farm Machinery and Equipment",
        "Renewable Energy in Agriculture",
        "Post-harvest Technology",
        "Organic agriculture",
        "Soil Health & Fertility Management",
        "Pest & Disease",
        "Integrated Pest Management (IPM)",
        "Crop Rotations & Intercropping",
        "Pollinator & Natural Enemy Habitat Creation",
        "Biodiversity Conservation",
        "Composting & Biofertilizer Production",
        "Weed Management",
        "Irrigation & Water Management",
        "Seed Saving & Variety Selection",
        "On-farm Research & Experimentation",
        "Organic Seed Saving",
        "Nutrient Cycling",
        "Composting and Vermicomposting",
    ],


    'Engineering': [
        // Add fields her
        "i) Aviation",

        "Aviation Transport",
        "Aviation Management",
        "Aviation Safety",
        "Aircraft Maintenance",
        "Air Traffic Control",
        "Airline Management & Operations",
        "Airport Management & Operations",
        "Unmanned Aerial Systems",
        "ii) Electrical Engineering",
        "Semiconductors",
        "Batteries & Fuel Cells",
        "Power Engineering",
        "Electronics Engineering",
        "Electronic Circuits",
        "Integrated Circuits/Microchips",
        "Signal Processing",
        "Microelectronics",
        "Computer Engineering",
        "Telecommunications Engineering",
        "Instrumentation Engineering",
        "Electro-Optics",
        "Distribution Engineering",
        "Wireless Sensor Networks",
        "Microwave Engineering",
        "Cold Regions Engineering",
        "Biological Engineering",
        "Engineering Education",
        "Engineering Physics",
        "iii) Civil engineering",
        "Urban Planning & Development",
        "Offshore Structures",

        "Hydraulic Engineering",
        "Geotechnical Engineering",
        "Structural Engineering",
        "Construction Engineering",
        "Civil Site Design",
        "Site Survey",
        "Earthquake Engineering",
        "Coastal Engineering",
        "Regional Planning & Development",
        "Ocean Engineering",
        "Petroleum Engineering",
        "Sound Design",
        "Remote Sensing",
        "Surveillance Systems",
        "iv) Automotive engineering",
        "i) Powertrain & Drivetrain:",
        "• Internal Combustion Engines (ICE):",
        "• Electric Vehicles (EVs):",
        "• Hybrid and Plug-in Hybrid Electric Vehicles (HEVs and PHEVs):",
        "• Transmission & Drivetrain Systems:",
        "ii) Vehicle Design & Engineering:",
        "• Chassis & Body Engineering:",
        "• Aerodynamics & Computational Fluid Dynamics (CFD):",
        "• Vehicle Dynamics & Control Systems:",
        "• Autonomous Driving & Advanced Driver-Assistance Systems (ADAS):",
        "iii) Manufacturing & Production:",
        "• Automotive Manufacturing Processes:",

        "• Supply Chain & Logistics:",
        "• Manufacturing Automation & Robotics:",
        "• Sustainable Manufacturing Practices:",
        "v) Electronics",
        "Circuit Design and Analysis:",
        "● Analog circuit design",
        "● Digital circuit design",
        "● Mixed-signal design",
        "● Power electronics design",
        "● RF and microwave circuit design",
        "● High-speed circuit design",
        "● FPGA and embedded systems design",
        "● Circuit simulation and modeling",
        "Electronics Manufacturing and Packaging:",
        "● PCB design and layout",
        "● Printed circuit board fabrication",
        "● Semiconductor fabrication",
        "● Component selection and sourcing",
        "● Assembly and soldering techniques",
        "● Test and measurement",
        "● Quality control and reliability",
        "Communication and Wireless Systems:",
        "● Mobile network infrastructure (2G/3G/4G/5G)",
        "● Wi-Fi and Bluetooth technology",
        "● Satellite communication systems",
        "● Radar and sensor technology",
        "● Optical communication systems",
        "● Signal processing and Modulation",

        "Embedded Systems and Robotics:",
        "● Microcontroller programming",
        "● Real-time operating systems",
        "● Sensor interfacing and data acquisition",
        "● Motor control and actuators",
        "● Control systems and feedback loops",
        "● Machine learning and AI for embedded systems",
        "Power Electronics and Energy Systems:",
        "● Power conversion (AC/DC, DC/DC)",
        "● Renewable energy systems (solar, wind)",
        "● Battery management systems",
        "● Power grid infrastructure",
        "● Smart grids and microgrids",
        "● Electric vehicle technology",
    ],


    'Energy': [
        // Add fields here
        "i) Solar Energy:",
        "● Photovoltaic (PV) Systems:",
        "● Concentrated Solar Power (CSP):",
        "● Solar Thermal Technologies:",
        "ii) Wind Energy:",
        "● Wind Turbine Technology:",
        "● Wind Resource Assessment:",
        "● Grid Integration and Power Management:",
        "iii) Hydropower:",
        "● Hydropower Plant Design and Construction:",
        "● Small Hydropower and Microhydro:",
        "● Hydropower Policy and Regulation:",
        "iv) Geothermal Energy:",
        "● Geothermal Resource Assessment:",
        "● Geothermal Power Plant Design and Operation:",
        "● Direct Use of Geothermal Energy:",
        "v) Biomass and Bioenergy:",
        "● Biomass Production and Processing:",
        "● Biofuels:",
        "● Biogas and Anaerobic Digestion:",
        "vi) Other Renewable Energy Technologies:",
        "● Ocean Energy:",
        "● Hydrogen Energy:",
        "● Energy Storage and Grid Integration:",
    ],


    


    'Food and beverage': [
        // Add fields here
        "i) Food Microbiology:",

        "Food Spoilage and Fermentation",
        "Probiotics and Prebiotics:",
        "Foodborne Pathogen Control",
        "ii) Food Processing and Engineering:",
        "Unit Operations in Food Processing:",
        "Food Packaging and Technology:",
        "Food Rheology and Texture:",
        "iii) Food Product Development:",
        "Sensory Science and Consumer Analysis:",
        "New Food Product Development",

        "Food Engineering",
        "● Food Additives",
        "● Nutrition Science",


        "● Food Preservation",
        "● Food Safety and toxicology",
        "● Flavor & Fragrance Chemistry",

        "● Dairy Science",
        "● Food Chemistry",
        "● Food Testing",
        "● Plant-Based Protein",
        "● Vegetarian & Vegan Nutrition",
        "● Food & Beverage Manufacturing",
        "● Nutritional Analysis",
        "● Recipe Formulation",
    ],


    'Healthcare': [
        "i) Public Health",
        "Epidemiology",
        "Environmental Epidemiology",
        "Pandemic Preparedness",
        "Emergency Preparedness",
        "Food Security",
        "Poverty Alleviation",
        "Disaster Relief",
        "Rural Development",
        "Contact Tracing",
        "Global Health",
        "Disease Control And Prevention",
        "Public Health and Sanitation",
        "Community Health Services",
        "Quality of Life Assessment",

        "Tobacco Use Prevention & Control",
        "Foodborne Disease",
        "ii) Public Safety",
        "Firefighting Equipment & Supplies",
        "Firefighting",
        "Law Enforcement",
        "Health Technology Assessment",
        "E-Health & Telemedicine",
        "iii) Occupational Health & Safety",
        "Industrial Hygiene",
        "Occupational Toxciology",
        "Construction Site Safety",
        "Biohazard Waste Management",
        "Workplace Safety Assessment",
        "Ergonomics",
        "Rural Health",
        "Healthcare Reimbursement",
        "iv) Psychiatry",
        "Psychotraumatology",
        "Child & Adolescent Psychiatry",
        "Neuropsychiatry",
        "Forensic Psychiatry",
        "Addiction Psychiatry",
        "Psychopharmacology",
        "Cognitive Behavioral Therapy",
        "Geriatric Psychiatry",
    ],


    'Medical devices and equipment': [
        "i) Device Types:",
        "● Implantable Devices:",
        "● Diagnostic Devices:",
        "● Therapeutic Devices:",
        "● Assistive Technologies:",
        "ii) Technology & Engineering:",
        "● Biomaterials:",
        "● Microfluidics & Nanotechnology:",
        "● Medical Imaging & Sensors:",
        "● Robotics & Artificial Intelligence:",
        "iii) Clinical Applications and Integration:",
        "● Cardiovascular Devices:",
        "● Neurological Devices:",
        "● Orthopedic Devices:",
        "● Rehabilitation Devices:",
        "● Point-of-Care Diagnostics:",

        "iv) Diagnostics & Monitoring:",
        "● Imaging devices:",
        "● Laboratory instruments:",
        "● Biosensors:",
        "● Vital signs monitors:",
        "v) Therapeutic & Interventional:",
        "● Implants:",
        "● Prosthetics & Orthotics:",
        "● Surgical instruments:",
        "● Respiratory support devices:",
        "● Dialysis machines:",

        "● Drug delivery systems:",
        "vi) Assistive & Rehabilitation:",
        "● Wheelchairs & mobility aids:",
        "● Hearing aids:",
        "● Vision aids:",
        "● Speech-generating devices:",
        "● Physical therapy equipment:",
        "vii) Personal & Home-based:",
        "● Blood glucose monitors:",
        "● Thermometers:",
        "● Blood pressure monitors:",
        "● Pregnancy tests:",
        "● Nebulizers:",
    ],


    


    'Sustainability science': [
        // Add fields here
        "i) Sustainability Solutions & Implementation:",
        "● Sustainable urban systems:",
        "● Sustainable agriculture and food systems:",
        "● Renewable energy and energy efficiency:",

        "● Water resource management",
        "ii) Other Areas of Expertise:",
        "● Life cycle assessment and industrial ecology:",
        "● Circular economy and waste management:",
        "● Climate change mitigation and adaptation:",
        "● Biodiversity conservation and ecosystem services",
    ]


    // Add other categories and subcategories as needed
};
